spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vicharstream
    username: postgres
    password: user123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxxxxxxxxxxxxxxxxxxxxxxx
    password: xxxx xxxx xxxx xxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false  # Serialize dates as ISO-8601 strings
      FAIL_ON_EMPTY_BEANS: false  # Do not fail if JSON has empty beans
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true  # Accept case-insensitive properties
      DEFAULT_VIEW_INCLUSION: true  # Include default views
    default-property-inclusion: NON_NULL  # Only include non-null properties in serialization
    default-use-wrapper: true  # Wrap primitive values

logging:
  level:
    org.springframework: INFO  # Set Spring Framework logging level to INFO
    com.payerup.server: DEBUG  # Set your application's logging level to DEBUG